// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: activity.queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO activity (
  created_at,
  space_id,
  public_id,
  member_id,
  action,
  entity_type,
  entity_id
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
) RETURNING id, created_at, space_id, public_id, member_id, "action", entity_type, entity_id
`

type CreateActivityParams struct {
	CreatedAt  time.Time
	SpaceID    int64
	PublicID   string
	MemberID   sql.NullInt64
	Action     string
	EntityType string
	EntityID   sql.NullInt64
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (Activity, error) {
	row := q.db.QueryRowContext(ctx, createActivity,
		arg.CreatedAt,
		arg.SpaceID,
		arg.PublicID,
		arg.MemberID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
	)
	var i Activity
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.SpaceID,
		&i.PublicID,
		&i.MemberID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
	)
	return i, err
}
