// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"
)

type Activity struct {
	ID         int64
	CreatedAt  time.Time
	SpaceID    int64
	PublicID   string
	MemberID   sql.NullInt64
	Action     string
	EntityType string
	EntityID   sql.NullInt64
}

type Member struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy sql.NullInt64
	UpdatedBy sql.NullInt64
	SpaceID   int64
	PublicID  string
	Name      string
}

type Note struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	CreatedBy sql.NullInt64
	UpdatedBy sql.NullInt64
	SpaceID   int64
	PublicID  string
	Title     string
	Content   string
}

type SchemaMigration struct {
	Version string
}

type Space struct {
	ID         int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Email      string
	AdminToken string
	EditToken  string
	ViewToken  string
	CreatedBy  sql.NullInt64
	UpdatedBy  sql.NullInt64
}
