// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: spaces.queries.sql

package db

import (
	"context"
	"time"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (
  created_at,
  updated_at,
  name,
  email,
  admin_token,
  edit_token,
  view_token
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
) RETURNING id, created_at, updated_at, name, email, admin_token, edit_token, view_token
`

type CreateSpaceParams struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Email      string
	AdminToken string
	EditToken  string
	ViewToken  string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Email,
		arg.AdminToken,
		arg.EditToken,
		arg.ViewToken,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.AdminToken,
		&i.EditToken,
		&i.ViewToken,
	)
	return i, err
}

const getSpaceByAccessToken = `-- name: GetSpaceByAccessToken :one
SELECT id, created_at, updated_at, name, email, admin_token, edit_token, view_token FROM spaces
WHERE admin_token = ?1
  OR edit_token = ?1
  OR view_token = ?1
LIMIT 1
`

func (q *Queries) GetSpaceByAccessToken(ctx context.Context, token string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByAccessToken, token)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.AdminToken,
		&i.EditToken,
		&i.ViewToken,
	)
	return i, err
}
