// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: spaces.queries.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (
  created_at,
  updated_at,
  name,
  email,
  admin_token,
  edit_token,
  view_token
) VALUES (
  ?1,
  ?2,
  ?3,
  ?4,
  ?5,
  ?6,
  ?7
) RETURNING id, created_at, updated_at, name, email, admin_token, edit_token, view_token, created_by, updated_by
`

type CreateSpaceParams struct {
	CreatedAt  time.Time
	UpdatedAt  time.Time
	Name       string
	Email      string
	AdminToken string
	EditToken  string
	ViewToken  string
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Email,
		arg.AdminToken,
		arg.EditToken,
		arg.ViewToken,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.AdminToken,
		&i.EditToken,
		&i.ViewToken,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const getSpaceByAccessToken = `-- name: GetSpaceByAccessToken :one
SELECT id, created_at, updated_at, name, email, admin_token, edit_token, view_token, created_by, updated_by FROM spaces
WHERE admin_token = ?1
  OR edit_token = ?1
  OR view_token = ?1
LIMIT 1
`

func (q *Queries) GetSpaceByAccessToken(ctx context.Context, token string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByAccessToken, token)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.AdminToken,
		&i.EditToken,
		&i.ViewToken,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces
SET updated_at = ?1,
  updated_by = ?2,
  name = ?3
WHERE id = ?4
RETURNING id, created_at, updated_at, name, email, admin_token, edit_token, view_token, created_by, updated_by
`

type UpdateSpaceParams struct {
	UpdatedAt time.Time
	UpdatedBy sql.NullInt64
	Name      string
	SpaceID   int64
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, updateSpace,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.Name,
		arg.SpaceID,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Email,
		&i.AdminToken,
		&i.EditToken,
		&i.ViewToken,
		&i.CreatedBy,
		&i.UpdatedBy,
	)
	return i, err
}

const updateSpaceCreatedBy = `-- name: UpdateSpaceCreatedBy :exec
UPDATE spaces
SET created_by = ?1,
  updated_by = ?1
WHERE id = ?2
`

type UpdateSpaceCreatedByParams struct {
	CreatedBy sql.NullInt64
	SpaceID   int64
}

func (q *Queries) UpdateSpaceCreatedBy(ctx context.Context, arg UpdateSpaceCreatedByParams) error {
	_, err := q.db.ExecContext(ctx, updateSpaceCreatedBy, arg.CreatedBy, arg.SpaceID)
	return err
}
