app = "simply-shared-notes"
primary_region = "ewr"

[env]
  DATABASE_URL="sqlite:/data/app.sqlite"
  DBMATE_MIGRATIONS_DIR="/migrations"
  DBMATE_NO_DUMP_SCHEMA="true"
  SMTP_HOST="smtp.mailgun.org"
  SMTP_PORT=587

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "simplysharednotes_data"
  destination = "/data"
