version: '3'

tasks:
  setup:
    desc: First time project setup
    cmds:
      - cp .env.sample .env
      - mkdir -p data

  build:
    desc: Build project
    sources:
      - "**/*.go"
    cmds:
      - go mod tidy
      - go build -o bin/app .
    deps:
      - templ
      - sqlc

  run:
    desc: Build and run project
    cmds:
      - go run .
    deps:
      - templ
      - sqlc

  live:
    desc: Run project with live reload
    env:
      PORT: 3001
    cmds:
      - templ generate --watch --proxyport="3000" --proxy="http://localhost:3001" --cmd="go run ." --open-browser=false
    deps:
      - sqlc

  templ:
    desc: Build templ files
    sources:
      - "views/**/*.templ"
    cmds:
      - templ generate

  assets:
    desc: Build frontend assets
    sources:
      - "assets/**/*.css"
      - "assets/**/*.js"
    cmds:
      - npm run build

  vite:
    desc: Run Vite development server
    cmds:
      - npm run dev

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/.vite dist/assets
 
  sqlc:
    desc: Generate code from SQL files
    sources:
      - "sql/schema.sql"
      - "sql/queries/**/*.sql"
    cmds:
      - sqlc generate

  migrate:
    desc: Run migrations (create database if does not exists)
    cmds:
      - dbmate migrate

  seed:
    desc: Load seed data for local development
    cmds:
      - sqlite3 data/app.sqlite < ./sql/seed.sql

  drop:
    desc: Delete database
    prompt: This will delete the database. Are you sure?
    cmds:
      - dbmate drop
  
  reset:
    desc: Resets database and seeds data
    cmds:
      - task: drop
      - task: migrate
      - task: seed
