// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

type SchemaMigration struct {
	Version string
}

type Space struct {
	ID         int64
	Name       string
	AdminToken string
}
