// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: spaces.queries.sql

package db

import (
	"context"
)

const getSpaceByAccessToken = `-- name: GetSpaceByAccessToken :one
SELECT id, name, admin_token FROM spaces
WHERE admin_token = ? LIMIT 1
`

func (q *Queries) GetSpaceByAccessToken(ctx context.Context, adminToken string) (Space, error) {
	row := q.db.QueryRowContext(ctx, getSpaceByAccessToken, adminToken)
	var i Space
	err := row.Scan(&i.ID, &i.Name, &i.AdminToken)
	return i, err
}
