name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Install Templ
        run: go install github.com/a-h/templ/cmd/templ@latest

      - name: Install sqlc
        run: go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Build
        run: task build 

