name: Validate

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24

      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Templ
        uses: jcwillox/install-tool-action@v1
        with:
          repo: a-h/templ
          download_url: "/releases/download/v{{version}}/templ_Linux_x86_64.tar.gz"
          version: 0.3.865

      - name: Install sqlc
        uses: jcwillox/install-tool-action@v1
        with:
          repo: sqlc-dev/sqlc
          download_url: "/releases/download/v{{version}}/sqlc_{{version}}_{{os}}_{{arch}}.{{archive}}"
          version: 1.28.0

      - name: Build
        run: task build

      - name: Check codegen committed
        run: git diff --exit-code
